---
title: "MTCars Analysis"
format: html
editor: visual
---

### Load in Libraries

```{r}
library(tidyverse)
library(plotly)
library(ggpubr)
```

### Read in Dataset

```{r}
mtcars <- datasets::mtcars
```

```{r}
?mtcars
```

Letʻs examine the relationship between weight and miles per gallon:

```{r}
mtcars_wt_mpg <- ggplot(data = mtcars, aes(x = mpg, y = wt)) +
  geom_point()

mtcars_wt_mpg
```

```{r}
ggplotly(mtcars_wt_mpg)
```

```{r}
mtcars <- mtcars %>% 
  tibble::rownames_to_column("model")
```

```{r}
mtcars_wt_mpg <- ggplot(data = mtcars, aes(x = mpg, y = wt, label = model, color = hp)) +
  geom_point() +
  geom_smooth() +
  stat_cor()

mtcars_wt_mpg
```

```{r}
mtcars_split <- mtcars %>%
  separate(model, into = c("make", "model"), sep = " ", extra = "merge", fill = "right")
```

### Challenge

What is the average mpg for each car manufactures? Please plot the results.

```{r}
average_mtcars_make_mpg <- mtcars_split %>% 
  group_by(make) %>% 
  summarise(average_mpg = mean(mpg, na.rm = TRUE))

ggplot(average_mtcars_make_mpg, aes(y = reorder(make, average_mpg), x = average_mpg)) +
  geom_bar(stat = "identity")
```
